language: node_js

node_js:
  - "9"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run-script build -- --prod --aot

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
